### ISSUE TITLE
net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: expected String, found token MAP_BEGIN instead

### ISSUE THREAD

**Issue by Him188** [Him188/yamlkt#8]
```stacktrace
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: expected String, found token MAP_BEGIN instead
managers: { }
          ^ at line 1, column 12

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder.nextString(YamlDecoder.kt:48)
	at net.mamoe.yamlkt.internal.YamlDecoder.nextStringOrNull(YamlDecoder.kt:837)
	at net.mamoe.yamlkt.internal.YamlDecoder.access$nextStringOrNull(YamlDecoder.kt:27)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.nextStringOrNull(YamlDecoder.kt:97)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeString(YamlDecoder.kt:114)
	at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:180)
	at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:177)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
	... 17 more

```

**Comment by Him188** [comment]
Input text: 
```yaml
managers: { }
```
